	SUBROUTINE fFCTRLS
	REAL*8 FCT(99),FACT(99),V
	COMMON /FCTRLS/ FCT , FACT
C
	FCT(1)=LOG(1.)
	FACT(1)=LOG(1.)
	  DO I=1,98
	  V=I
	  FACT(I+1)=FACT(I)+LOG(SQRT(V))
	  FCT(I+1)=LOG(V)-LOG(10.)+FCT(I)
	  END DO
	RETURN
	END
